### ISSUE TITLE
doesn't work on R version 4.0?

### ISSUE THREAD

**Issue by btojenniferborder** [slisovski/GeoLocTools#1]
Hi, I downloaded this package and it all worked fine for R3.6.3 but for R 4.0.0 I keep getting this error when I run setupGeolocation():

Downloading GitHub repo SLisovski/GeoLight@Update_2.01
√  checking for file 'C:\Users\Jenni Border\AppData\Local\Temp\Rtmpi2HJZ9\remotes34d86c627889\slisovski-GeoLight-9105251/DESCRIPTION' (526ms)
-  preparing 'GeoLight': (553ms)
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts (602ms)
-  checking for empty or unneeded directories
-  building 'GeoLight_2.0.1.tar.gz'
   
Error: Failed to install 'GeoLight' from GitHub:
  (converted from warning) package ‘GeoLight’ is in use and will not be installed
In addition: Warning message:
In data(wrld_simpl) : data set ‘wrld_simpl’ not found

Note this is not caused by the package already being loaded- this is a new R session where nothing has yet been loaded and this is the first command.

**Comment by slisovski** [comment]
The R package "GeoLight" as already loaded and cannot be updated. Either restart R and do not call
```
library(GeoLight)
```
or unload the package
```
detach("package:GeoLight", unload = T)
```

**Comment by btojenniferborder** [comment]
That still doesn't work. In a new R session all I am typing in is:
library(GeoLocTools)
setupGeolocation()

so GeoLight should not already be loaded. When I tried detach I still got an error:

detach("package:GeoLight", unload = T)
Error in detach("package:GeoLight", unload = T) : invalid 'name' argument
> library(GeoLocTools)
> setupGeolocation()
Downloading GitHub repo SLisovski/GeoLight@Update_2.01
√  checking for file 'C:\Users\Jenni Border\AppData\Local\Temp\Rtmps7UiHw\remotesa645fa36c3c\slisovski-GeoLight-9105251/DESCRIPTION' (529ms)
-  preparing 'GeoLight': (517ms)
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts (566ms)
-  checking for empty or unneeded directories
-  building 'GeoLight_2.0.1.tar.gz'
   
Error: Failed to install 'GeoLight' from GitHub:
  (converted from warning) package ‘GeoLight’ is in use and will not be installed
In addition: Warning message:
In data(wrld_simpl) : data set ‘wrld_simpl’ not found
> detach("package:GeoLight", unload = T)
Error: package ‘GeoLight’ is required by ‘PolarGeolocation’ so will not be detached

**Comment by slisovski** [comment]
could you lease post your sessionInfo()

**Comment by btojenniferborder** [comment]
This is the session info after the lines of code:
library(GeoLocTools)
setupGeolocation()


> session_info()
- Session info ------------------------------------------------------------------------------------
 setting  value                       
 version  R version 4.0.0 (2020-04-24)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United Kingdom.1252 
 ctype    English_United Kingdom.1252 
 tz       Europe/London               
 date     2020-05-19                  

- Packages ----------------------------------------------------------------------------------------
 package          * version     date       lib source                                     
 assertthat         0.2.1       2019-03-21 [1] CRAN (R 4.0.0)                             
 backports          1.1.6       2020-04-05 [1] CRAN (R 4.0.0)                             
 bit              * 1.1-15.2    2020-02-10 [1] CRAN (R 4.0.0)                             
 bitops             1.0-6       2013-08-17 [1] CRAN (R 4.0.0)                             
 boot             * 1.3-24      2019-12-20 [2] CRAN (R 4.0.0)                             
 callr              3.4.3       2020-03-28 [1] CRAN (R 4.0.0)                             
 changepoint        2.2.2       2016-10-04 [1] CRAN (R 4.0.0)                             
 CircStats        * 0.2-6       2018-07-01 [1] CRAN (R 4.0.0)                             
 circular         * 0.4-93      2017-06-29 [1] CRAN (R 4.0.0)                             
 class              7.3-16      2020-03-25 [2] CRAN (R 4.0.0)                             
 classInt           0.4-3       2020-04-07 [1] CRAN (R 4.0.0)                             
 cli                2.0.2       2020-02-28 [1] CRAN (R 4.0.0)                             
 coda               0.19-3      2019-07-05 [1] CRAN (R 4.0.0)                             
 codetools          0.2-16      2018-12-24 [2] CRAN (R 4.0.0)                             
 colorspace         1.4-1       2019-03-18 [1] CRAN (R 4.0.0)                             
 crayon             1.3.4       2017-09-16 [1] CRAN (R 4.0.0)                             
 curl               4.3         2019-12-02 [1] CRAN (R 4.0.0)                             
 DBI                1.1.0       2019-12-15 [1] CRAN (R 4.0.0)                             
 desc               1.2.0       2018-05-01 [1] CRAN (R 4.0.0)                             
 devtools         * 2.3.0       2020-04-10 [1] CRAN (R 4.0.0)                             
 digest           * 0.6.25      2020-02-23 [1] CRAN (R 4.0.0)                             
 dotCall64        * 1.0-0       2018-07-30 [1] CRAN (R 4.0.0)                             
 dplyr              0.8.5       2020-03-07 [1] CRAN (R 4.0.0)                             
 e1071              1.7-3       2019-11-26 [1] CRAN (R 4.0.0)                             
 ellipsis           0.3.0       2019-09-20 [1] CRAN (R 4.0.0)                             
 fansi              0.4.1       2020-01-08 [1] CRAN (R 4.0.0)                             
 fields           * 10.3        2020-02-04 [1] CRAN (R 4.0.0)                             
 forecast         * 8.12        2020-03-31 [1] CRAN (R 4.0.0)                             
 foreign            0.8-78      2020-04-13 [2] CRAN (R 4.0.0)                             
 fracdiff           1.5-1       2020-01-24 [1] CRAN (R 4.0.0)                             
 fs                 1.4.1       2020-04-04 [1] CRAN (R 4.0.0)                             
 gdtools            0.2.2       2020-04-03 [1] CRAN (R 4.0.0)                             
 GeoLight         * 2.0.0       2015-09-06 [1] CRAN (R 4.0.0)                             
 GeoLocTools      * 0.1.0       2020-05-19 [1] Github (SLisovski/GeoLocTools@7d4e746)     
 geosphere        * 1.5-10      2019-05-26 [1] CRAN (R 4.0.0)                             
 ggmap            * 3.0.0       2019-02-04 [1] CRAN (R 4.0.0)                             
 ggplot2          * 3.3.0       2020-03-05 [1] CRAN (R 4.0.0)                             
 ggsn             * 0.5.0       2019-02-18 [1] CRAN (R 4.0.0)                             
 glue               1.4.1       2020-05-13 [1] CRAN (R 4.0.0)                             
 gtable             0.3.0       2019-03-25 [1] CRAN (R 4.0.0)                             
 httr               1.4.1       2019-08-05 [1] CRAN (R 4.0.0)                             
 jpeg               0.1-8.1     2019-10-24 [1] CRAN (R 4.0.0)                             
 KernSmooth         2.23-16     2019-10-15 [2] CRAN (R 4.0.0)                             
 lattice            0.20-41     2020-04-02 [2] CRAN (R 4.0.0)                             
 lifecycle          0.2.0       2020-03-06 [1] CRAN (R 4.0.0)                             
 lmtest             0.9-37      2019-04-30 [1] CRAN (R 4.0.0)                             
 magrittr           1.5         2014-11-22 [1] CRAN (R 4.0.0)                             
 mapdata          * 2.3.0       2018-03-30 [1] CRAN (R 4.0.0)                             
 maps             * 3.3.0       2018-04-03 [1] CRAN (R 4.0.0)                             
 maptools         * 0.9-9       2019-12-01 [1] CRAN (R 4.0.0)                             
 MASS             * 7.3-51.5    2019-12-20 [2] CRAN (R 4.0.0)                             
 memoise            1.1.0       2017-04-21 [1] CRAN (R 4.0.0)                             
 munsell            0.5.0       2018-06-12 [1] CRAN (R 4.0.0)                             
 mvtnorm            1.1-0       2020-02-24 [1] CRAN (R 4.0.0)                             
 ncdf4            * 1.17        2019-10-23 [1] CRAN (R 4.0.0)                             
 nlme               3.1-147     2020-04-13 [2] CRAN (R 4.0.0)                             
 nnet               7.3-13      2020-02-25 [2] CRAN (R 4.0.0)                             
 pillar             1.4.3       2019-12-20 [1] CRAN (R 4.0.0)                             
 pkgbuild           1.0.8       2020-05-07 [1] CRAN (R 4.0.0)                             
 pkgconfig          2.0.3       2019-09-22 [1] CRAN (R 4.0.0)                             
 pkgload            1.0.2       2018-10-29 [1] CRAN (R 4.0.0)                             
 plyr               1.8.6       2020-03-03 [1] CRAN (R 4.0.0)                             
 png                0.1-7       2013-12-03 [1] CRAN (R 4.0.0)                             
 PolarGeolocation * 0.1.0       2020-05-19 [1] Github (SLisovski/PolarGeolocation@6f321f0)
 prettyunits        1.1.1       2020-01-24 [1] CRAN (R 4.0.0)                             
 probGLS          * 0.9.5       2020-05-19 [1] Github (benjamin-merkel/probGLS@b3808f6)   
 processx           3.4.2       2020-02-09 [1] CRAN (R 4.0.0)                             
 ps                 1.3.3       2020-05-08 [1] CRAN (R 4.0.0)                             
 purrr              0.3.4       2020-04-17 [1] CRAN (R 4.0.0)                             
 quadprog           1.5-8       2019-11-20 [1] CRAN (R 4.0.0)                             
 quantmod           0.4.17      2020-03-31 [1] CRAN (R 4.0.0)                             
 R6                 2.4.1       2019-11-12 [1] CRAN (R 4.0.0)                             
 raster           * 3.1-5       2020-04-19 [1] CRAN (R 4.0.0)                             
 Rcpp             * 1.0.4.6     2020-04-09 [1] CRAN (R 4.0.0)                             
 RcppArmadillo    * 0.9.870.2.0 2020-04-27 [1] CRAN (R 4.0.0)                             
 remotes            2.1.1       2020-02-15 [1] CRAN (R 4.0.0)                             
 rgdal            * 1.4-8       2019-11-27 [1] CRAN (R 4.0.0)                             
 rgeos            * 0.5-2       2019-10-03 [1] CRAN (R 4.0.0)                             
 RgoogleMaps        1.4.5.3     2020-02-12 [1] CRAN (R 4.0.0)                             
 rjson              0.2.20      2018-06-08 [1] CRAN (R 4.0.0)                             
 rlang              0.4.5       2020-03-01 [1] CRAN (R 4.0.0)                             
 rprojroot          1.3-2       2018-01-03 [1] CRAN (R 4.0.0)                             
 rstudioapi         0.11        2020-02-07 [1] CRAN (R 4.0.0)                             
 scales             1.1.0       2019-11-18 [1] CRAN (R 4.0.0)                             
 sessioninfo        1.1.1       2018-11-05 [1] CRAN (R 4.0.0)                             
 sf                 0.9-2       2020-04-14 [1] CRAN (R 4.0.0)                             
 SGAT             * 0.1.3       2020-05-04 [1] Github (SWotherspoon/SGAT@952d6f4)         
 sp               * 1.4-1       2020-02-28 [1] CRAN (R 4.0.0)                             
 spam             * 2.5-1       2019-12-12 [1] CRAN (R 4.0.0)                             
 stringi            1.4.6       2020-02-17 [1] CRAN (R 4.0.0)                             
 stringr          * 1.4.0       2019-02-10 [1] CRAN (R 4.0.0)                             
 svglite          * 1.2.3       2020-02-07 [1] CRAN (R 4.0.0)                             
 systemfonts        0.2.1       2020-04-29 [1] CRAN (R 4.0.0)                             
 testthat           2.3.2       2020-03-02 [1] CRAN (R 4.0.0)                             
 tibble             3.0.1       2020-04-20 [1] CRAN (R 4.0.0)                             
 tidyr              1.0.2       2020-01-24 [1] CRAN (R 4.0.0)                             
 tidyselect         1.0.0       2020-01-27 [1] CRAN (R 4.0.0)                             
 timeDate           3043.102    2018-02-21 [1] CRAN (R 4.0.0)                             
 truncnorm        * 1.0-8       2018-02-27 [1] CRAN (R 4.0.0)                             
 tseries            0.10-47     2019-06-05 [1] CRAN (R 4.0.0)                             
 TTR                0.23-6      2019-12-15 [1] CRAN (R 4.0.0)                             
 TwGeos           * 0.1.2       2020-05-19 [1] Github (SLisovski/TwGeos@8facef4)          
 units              0.6-6       2020-03-16 [1] CRAN (R 4.0.0)                             
 urca               1.3-0       2016-09-06 [1] CRAN (R 4.0.0)                             
 usethis          * 1.6.1       2020-04-29 [1] CRAN (R 4.0.0)                             
 vctrs              0.2.4       2020-03-10 [1] CRAN (R 4.0.0)                             
 withr              2.2.0       2020-04-20 [1] CRAN (R 4.0.0)                             
 xts                0.12-0      2020-01-19 [1] CRAN (R 4.0.0)                             
 zoo              * 1.8-8       2020-05-02 [1] CRAN (R 4.0.0)                             

[1] C:/Users/Jenni Border/Documents/R/win-library/4.0
[2] C:/Program Files/R/R-4.0.0/library

**Comment by slisovski** [comment]
Sorry, can you do `sessionInfo()` instead of `session_info()`

**Comment by btojenniferborder** [comment]
Sorry, here:
R version 4.0.0 (2020-04-24)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] parallel  grid      stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] PolarGeolocation_0.1.0    zoo_1.8-8                 TwGeos_0.1.2             
 [4] probGLS_0.9.5             stringr_1.4.0             ncdf4_1.17               
 [7] GeoLight_2.0.0            SGAT_0.1.3                svglite_1.2.3            
[10] rgeos_0.5-2               maptools_0.9-9            ggsn_0.5.0               
[13] ggmap_3.0.0               ggplot2_3.3.0             RcppArmadillo_0.9.870.2.0
[16] Rcpp_1.0.4.6              CircStats_0.2-6           boot_1.3-24              
[19] MASS_7.3-51.5             rgdal_1.4-8               bit_1.1-15.2             
[22] truncnorm_1.0-8           circular_0.4-93           mapdata_2.3.0            
[25] forecast_8.12             fields_10.3               maps_3.3.0               
[28] spam_2.5-1                dotCall64_1.0-0           raster_3.1-5             
[31] sp_1.4-1                  geosphere_1.5-10          digest_0.6.25            
[34] devtools_2.3.0            usethis_1.6.1             GeoLocTools_0.1.0        

loaded via a namespace (and not attached):
 [1] nlme_3.1-147        bitops_1.0-6        fs_1.4.1            sf_0.9-2           
 [5] xts_0.12-0          httr_1.4.1          rprojroot_1.3-2     tools_4.0.0        
 [9] backports_1.1.6     R6_2.4.1            KernSmooth_2.23-16  DBI_1.1.0          
[13] colorspace_1.4-1    nnet_7.3-13         withr_2.2.0         tidyselect_1.0.0   
[17] prettyunits_1.1.1   processx_3.4.2      curl_4.3            compiler_4.0.0     
[21] cli_2.0.2           desc_1.2.0          tseries_0.10-47     scales_1.1.0       
[25] classInt_0.4-3      lmtest_0.9-37       fracdiff_1.5-1      mvtnorm_1.1-0      
[29] quadprog_1.5-8      callr_3.4.3         systemfonts_0.2.1   foreign_0.8-78     
[33] jpeg_0.1-8.1        pkgconfig_2.0.3     changepoint_2.2.2   sessioninfo_1.1.1  
[37] rlang_0.4.5         TTR_0.23-6          rstudioapi_0.11     quantmod_0.4.17    
[41] dplyr_0.8.5         magrittr_1.5        munsell_0.5.0       fansi_0.4.1        
[45] gdtools_0.2.2       lifecycle_0.2.0     stringi_1.4.6       pkgbuild_1.0.8     
[49] plyr_1.8.6          crayon_1.3.4        lattice_0.20-41     ps_1.3.3           
[53] pillar_1.4.3        rjson_0.2.20        codetools_0.2-16    pkgload_1.0.2      
[57] urca_1.3-0          glue_1.4.1          remotes_2.1.1       png_0.1-7          
[61] vctrs_0.2.4         testthat_2.3.2      RgoogleMaps_1.4.5.3 gtable_0.3.0       
[65] purrr_0.3.4         tidyr_1.0.2         assertthat_0.2.1    e1071_1.7-3        
[69] coda_0.19-3         class_7.3-16        timeDate_3043.102   tibble_3.0.1       
[73] memoise_1.1.0       units_0.6-6         ellipsis_0.3.0

**Comment by slisovski** [comment]
Maybe an easy fix for the moment:
Restart R
```
devtools::install_github("SLisovski/GeoLight", ref = "Update_2.01")
```
then
```
library(GeoLocTools)
setupGeolocation()
```

**Comment by btojenniferborder** [comment]
Thanks! That works fine now.
